- name: Update APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: False

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ispconfig_web_packages }}"

- apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ispconfig_web_apache_modules }}"
